//go:build wireinject
// +build wireinject

package wire

import (
	"goadmin/pkg/task"

	"github.com/google/wire"
)

// App represents the application container with all necessary dependencies.
type App struct {
	ServiceManager *task.ServiceManager
}

// InitializeApp initializes the application with all dependencies.
// This function is generated by Wire using wire.Build.
func InitializeApp() (*App, error) {
	wire.Build(
		AppSet,
		wire.Struct(new(App), "*"),
	)
	return &App{}, nil
}